// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGaG31eiMMMkkCKnW4XpRpi8wghhk8mQI',
    appId: '1:69902482168:web:b02d2f5fb50be0d992590d',
    messagingSenderId: '69902482168',
    projectId: 'thought-speech',
    authDomain: 'thought-speech.firebaseapp.com',
    storageBucket: 'thought-speech.appspot.com',
    measurementId: 'G-J8ZMKCJCEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGtY1aul1qBS1qB4qvSGXMGL9RB__0HKw',
    appId: '1:69902482168:android:7764d67119475ec692590d',
    messagingSenderId: '69902482168',
    projectId: 'thought-speech',
    storageBucket: 'thought-speech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIKNDyu9T7XNGQmFUG7w2NhHXyGjEV1vk',
    appId: '1:69902482168:ios:19be1ce36aaf77c592590d',
    messagingSenderId: '69902482168',
    projectId: 'thought-speech',
    storageBucket: 'thought-speech.appspot.com',
    iosClientId: '69902482168-1tgvfqme6m5lv1kb7cejb705c4bvi1ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.thoughtspeech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIKNDyu9T7XNGQmFUG7w2NhHXyGjEV1vk',
    appId: '1:69902482168:ios:19be1ce36aaf77c592590d',
    messagingSenderId: '69902482168',
    projectId: 'thought-speech',
    storageBucket: 'thought-speech.appspot.com',
    iosClientId: '69902482168-1tgvfqme6m5lv1kb7cejb705c4bvi1ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.thoughtspeech',
  );
}
